### ISSUE TITLE
Build of android application

### ISSUE THREAD

**Issue by pan-** [ARMmbed/connectedhomeip#112]
Instructions must be available in the Wiki

**Comment by fkjagodzinski** [comment]
What about the task from the issue description? Shall we reopen this ticket until the wiki is updated?

**Comment by pan-** [comment]
Yes we should. I moved the task back to In progress.

**Comment by fkjagodzinski** [comment]
Ok, I added [**a short apk build guide**](https://github.com/ARMmbed/connectedhomeip/wiki/The-easiest-way-to-build-Android-CHIPTool-app) to our wiki.

Turns out it is quite simple if you follow the GitHub action workflow and use a Docker image. I did not reference [the official build guide](https://github.com/project-chip/connectedhomeip/blob/master/src/android/CHIPTool/README.md) on purpose as it has quite a few ambiguities for people not familiar with Android build tools/IDEs.
