### ISSUE TITLE
[Artur] GN: Suggestion for application to Mbed integration

### ISSUE THREAD

**Issue by pan-** [ARMmbed/connectedhomeip#4]

**Comment by ATmobica** [comment]
My first suggestion about example application directory (for example: example/shell/mbed):
1. Use Cmake build system for  mbed application example
2. CMakeList of mbed example should be modified - use environment mbed path, add CHIP root path, include path to CHIP library cmake, link CHIP library to project
3. Create a symlink to CHIP root (mbed/third_party/connectedhomeip - according to the design)
4. I would personally start with custom main.cpp file (some simplest implementation using CHIP) than integrated it with shell common files

**Comment by ATmobica** [comment]
Next suggestions:
1. Point 3. from the previous note is not correct due to the problem with symlinks inside mbed project [symblink issue](https://github.com/ARMmbed/connectedhomeip/wiki/Symbolic-link-issues)
2. CMakeList of mbed example should add a subdirectory to Mbed config directory - Cmake and GN connecting layer
3.  Mbed config directory - add CMakeLists which prepares CHIP build configuration and defines 'chip-gn' target that builds CHIP library and defines 'chip' target that exposes CHIP headers & libraries to the application; add CHIP GN "project" to build GN library

**Comment by ATmobica** [comment]
I think we should also consider creating some cmake extension functions (like the zephyr platform [extensions.cmake](https://elixir.bootlin.com/zephyr/v2.5.0-rc1/source/cmake/extensions.cmake). They may be useful in getting for example compilation flags that should be passed to GN build.

**Comment by pan-** [comment]
The compilation flags should be propagated to the gn build through mbed. The flags and helpers are defined in this folder: https://github.com/ARMmbed/mbed-os/tree/master/tools/cmake
